// Generated by `wit-bindgen` 0.17.0. DO NOT EDIT!
#include "p2fs.h"


__attribute__((__import_module__("wasi:io/error@0.2.0"), __import_name__("[method]error.to-debug-string")))
extern void __wasm_import_wasi_io_error_method_error_to_debug_string(int32_t, int32_t);

__attribute__((__import_module__("wasi:io/poll@0.2.0"), __import_name__("[method]pollable.ready")))
extern int32_t __wasm_import_wasi_io_poll_method_pollable_ready(int32_t);

__attribute__((__import_module__("wasi:io/poll@0.2.0"), __import_name__("[method]pollable.block")))
extern void __wasm_import_wasi_io_poll_method_pollable_block(int32_t);

__attribute__((__import_module__("wasi:io/poll@0.2.0"), __import_name__("poll")))
extern void __wasm_import_wasi_io_poll_poll(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.read")))
extern void __wasm_import_wasi_io_streams_method_input_stream_read(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.blocking-read")))
extern void __wasm_import_wasi_io_streams_method_input_stream_blocking_read(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.skip")))
extern void __wasm_import_wasi_io_streams_method_input_stream_skip(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.blocking-skip")))
extern void __wasm_import_wasi_io_streams_method_input_stream_blocking_skip(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]input-stream.subscribe")))
extern int32_t __wasm_import_wasi_io_streams_method_input_stream_subscribe(int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.check-write")))
extern void __wasm_import_wasi_io_streams_method_output_stream_check_write(int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.write")))
extern void __wasm_import_wasi_io_streams_method_output_stream_write(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.blocking-write-and-flush")))
extern void __wasm_import_wasi_io_streams_method_output_stream_blocking_write_and_flush(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.flush")))
extern void __wasm_import_wasi_io_streams_method_output_stream_flush(int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.blocking-flush")))
extern void __wasm_import_wasi_io_streams_method_output_stream_blocking_flush(int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.subscribe")))
extern int32_t __wasm_import_wasi_io_streams_method_output_stream_subscribe(int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.write-zeroes")))
extern void __wasm_import_wasi_io_streams_method_output_stream_write_zeroes(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.blocking-write-zeroes-and-flush")))
extern void __wasm_import_wasi_io_streams_method_output_stream_blocking_write_zeroes_and_flush(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.splice")))
extern void __wasm_import_wasi_io_streams_method_output_stream_splice(int32_t, int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[method]output-stream.blocking-splice")))
extern void __wasm_import_wasi_io_streams_method_output_stream_blocking_splice(int32_t, int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:clocks/wall-clock@0.2.0"), __import_name__("now")))
extern void __wasm_import_wasi_clocks_wall_clock_now(int32_t);

__attribute__((__import_module__("wasi:clocks/wall-clock@0.2.0"), __import_name__("resolution")))
extern void __wasm_import_wasi_clocks_wall_clock_resolution(int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.read-via-stream")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_read_via_stream(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.write-via-stream")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_write_via_stream(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.append-via-stream")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_append_via_stream(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.advise")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_advise(int32_t, int64_t, int64_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.sync-data")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_sync_data(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.get-flags")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_get_flags(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.get-type")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_get_type(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.set-size")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_set_size(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.set-times")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_set_times(int32_t, int32_t, int64_t, int32_t, int32_t, int64_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.read")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_read(int32_t, int64_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.write")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_write(int32_t, int32_t, int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.read-directory")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_read_directory(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.sync")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_sync(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.create-directory-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_create_directory_at(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.stat")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_stat(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.stat-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_stat_at(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.set-times-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_set_times_at(int32_t, int32_t, int32_t, int32_t, int32_t, int64_t, int32_t, int32_t, int64_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.link-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_link_at(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.open-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_open_at(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.readlink-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_readlink_at(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.remove-directory-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_remove_directory_at(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.rename-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_rename_at(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.symlink-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_symlink_at(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.unlink-file-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_unlink_file_at(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.is-same-object")))
extern int32_t __wasm_import_wasi_filesystem_types_method_descriptor_is_same_object(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.metadata-hash")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_metadata_hash(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]descriptor.metadata-hash-at")))
extern void __wasm_import_wasi_filesystem_types_method_descriptor_metadata_hash_at(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[method]directory-entry-stream.read-directory-entry")))
extern void __wasm_import_wasi_filesystem_types_method_directory_entry_stream_read_directory_entry(int32_t, int32_t);

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("filesystem-error-code")))
extern void __wasm_import_wasi_filesystem_types_filesystem_error_code(int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("wasi:io/error@0.2.0"), __import_name__("[resource-drop]error")))
extern void __wasm_import_wasi_io_error_error_drop(int32_t handle);

void wasi_io_error_error_drop_own(wasi_io_error_own_error_t handle) {
  __wasm_import_wasi_io_error_error_drop(handle.__handle);
}

wasi_io_error_borrow_error_t wasi_io_error_borrow_error(wasi_io_error_own_error_t arg) {
  return (wasi_io_error_borrow_error_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:io/poll@0.2.0"), __import_name__("[resource-drop]pollable")))
extern void __wasm_import_wasi_io_poll_pollable_drop(int32_t handle);

void wasi_io_poll_pollable_drop_own(wasi_io_poll_own_pollable_t handle) {
  __wasm_import_wasi_io_poll_pollable_drop(handle.__handle);
}

wasi_io_poll_borrow_pollable_t wasi_io_poll_borrow_pollable(wasi_io_poll_own_pollable_t arg) {
  return (wasi_io_poll_borrow_pollable_t) { arg.__handle };
}

void wasi_io_poll_list_borrow_pollable_free(wasi_io_poll_list_borrow_pollable_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void p2fs_list_u32_free(p2fs_list_u32_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wasi_io_streams_stream_error_free(wasi_io_streams_stream_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
  }
}

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[resource-drop]input-stream")))
extern void __wasm_import_wasi_io_streams_input_stream_drop(int32_t handle);

void wasi_io_streams_input_stream_drop_own(wasi_io_streams_own_input_stream_t handle) {
  __wasm_import_wasi_io_streams_input_stream_drop(handle.__handle);
}

wasi_io_streams_borrow_input_stream_t wasi_io_streams_borrow_input_stream(wasi_io_streams_own_input_stream_t arg) {
  return (wasi_io_streams_borrow_input_stream_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:io/streams@0.2.0"), __import_name__("[resource-drop]output-stream")))
extern void __wasm_import_wasi_io_streams_output_stream_drop(int32_t handle);

void wasi_io_streams_output_stream_drop_own(wasi_io_streams_own_output_stream_t handle) {
  __wasm_import_wasi_io_streams_output_stream_drop(handle.__handle);
}

wasi_io_streams_borrow_output_stream_t wasi_io_streams_borrow_output_stream(wasi_io_streams_own_output_stream_t arg) {
  return (wasi_io_streams_borrow_output_stream_t) { arg.__handle };
}

void p2fs_list_u8_free(p2fs_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wasi_io_streams_result_list_u8_stream_error_free(wasi_io_streams_result_list_u8_stream_error_t *ptr) {
  if (!ptr->is_err) {
    p2fs_list_u8_free(&ptr->val.ok);
  } else {
    wasi_io_streams_stream_error_free(&ptr->val.err);
  }
}

void wasi_io_streams_result_u64_stream_error_free(wasi_io_streams_result_u64_stream_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasi_io_streams_stream_error_free(&ptr->val.err);
  }
}

void wasi_io_streams_result_void_stream_error_free(wasi_io_streams_result_void_stream_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasi_io_streams_stream_error_free(&ptr->val.err);
  }
}

void wasi_filesystem_types_option_datetime_free(wasi_filesystem_types_option_datetime_t *ptr) {
  if (ptr->is_some) {
  }
}

void wasi_filesystem_types_descriptor_stat_free(wasi_filesystem_types_descriptor_stat_t *ptr) {
  wasi_filesystem_types_option_datetime_free(&ptr->data_access_timestamp);
  wasi_filesystem_types_option_datetime_free(&ptr->data_modification_timestamp);
  wasi_filesystem_types_option_datetime_free(&ptr->status_change_timestamp);
}

void wasi_filesystem_types_new_timestamp_free(wasi_filesystem_types_new_timestamp_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 2: {
      break;
    }
  }
}

void wasi_filesystem_types_directory_entry_free(wasi_filesystem_types_directory_entry_t *ptr) {
  p2fs_string_free(&ptr->name);
}

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[resource-drop]descriptor")))
extern void __wasm_import_wasi_filesystem_types_descriptor_drop(int32_t handle);

void wasi_filesystem_types_descriptor_drop_own(wasi_filesystem_types_own_descriptor_t handle) {
  __wasm_import_wasi_filesystem_types_descriptor_drop(handle.__handle);
}

wasi_filesystem_types_borrow_descriptor_t wasi_filesystem_types_borrow_descriptor(wasi_filesystem_types_own_descriptor_t arg) {
  return (wasi_filesystem_types_borrow_descriptor_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:filesystem/types@0.2.0"), __import_name__("[resource-drop]directory-entry-stream")))
extern void __wasm_import_wasi_filesystem_types_directory_entry_stream_drop(int32_t handle);

void wasi_filesystem_types_directory_entry_stream_drop_own(wasi_filesystem_types_own_directory_entry_stream_t handle) {
  __wasm_import_wasi_filesystem_types_directory_entry_stream_drop(handle.__handle);
}

wasi_filesystem_types_borrow_directory_entry_stream_t wasi_filesystem_types_borrow_directory_entry_stream(wasi_filesystem_types_own_directory_entry_stream_t arg) {
  return (wasi_filesystem_types_borrow_directory_entry_stream_t) { arg.__handle };
}

void wasi_filesystem_types_result_own_input_stream_error_code_free(wasi_filesystem_types_result_own_input_stream_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_own_output_stream_error_code_free(wasi_filesystem_types_result_own_output_stream_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_void_error_code_free(wasi_filesystem_types_result_void_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_descriptor_flags_error_code_free(wasi_filesystem_types_result_descriptor_flags_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_descriptor_type_error_code_free(wasi_filesystem_types_result_descriptor_type_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_tuple2_list_u8_bool_error_code_free(wasi_filesystem_types_result_tuple2_list_u8_bool_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_filesize_error_code_free(wasi_filesystem_types_result_filesize_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_own_directory_entry_stream_error_code_free(wasi_filesystem_types_result_own_directory_entry_stream_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_descriptor_stat_error_code_free(wasi_filesystem_types_result_descriptor_stat_error_code_t *ptr) {
  if (!ptr->is_err) {
    wasi_filesystem_types_descriptor_stat_free(&ptr->val.ok);
  } else {
  }
}

void wasi_filesystem_types_result_own_descriptor_error_code_free(wasi_filesystem_types_result_own_descriptor_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_result_string_error_code_free(wasi_filesystem_types_result_string_error_code_t *ptr) {
  if (!ptr->is_err) {
    p2fs_string_free(&ptr->val.ok);
  } else {
  }
}

void wasi_filesystem_types_result_metadata_hash_value_error_code_free(wasi_filesystem_types_result_metadata_hash_value_error_code_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_filesystem_types_option_directory_entry_free(wasi_filesystem_types_option_directory_entry_t *ptr) {
  if (ptr->is_some) {
    wasi_filesystem_types_directory_entry_free(&ptr->val);
  }
}

void wasi_filesystem_types_result_option_directory_entry_error_code_free(wasi_filesystem_types_result_option_directory_entry_error_code_t *ptr) {
  if (!ptr->is_err) {
    wasi_filesystem_types_option_directory_entry_free(&ptr->val.ok);
  } else {
  }
}

void wasi_filesystem_types_option_error_code_free(wasi_filesystem_types_option_error_code_t *ptr) {
  if (ptr->is_some) {
  }
}

void p2fs_string_set(p2fs_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void p2fs_string_dup(p2fs_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void p2fs_string_free(p2fs_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void wasi_io_error_method_error_to_debug_string(wasi_io_error_borrow_error_t self, p2fs_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_error_method_error_to_debug_string((self).__handle, ptr);
  *ret = (p2fs_string_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

bool wasi_io_poll_method_pollable_ready(wasi_io_poll_borrow_pollable_t self) {
  int32_t ret = __wasm_import_wasi_io_poll_method_pollable_ready((self).__handle);
  return ret;
}

void wasi_io_poll_method_pollable_block(wasi_io_poll_borrow_pollable_t self) {
  __wasm_import_wasi_io_poll_method_pollable_block((self).__handle);
}

void wasi_io_poll_poll(wasi_io_poll_list_borrow_pollable_t *in, p2fs_list_u32_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_poll_poll((int32_t) (*in).ptr, (int32_t) (*in).len, ptr);
  *ret = (p2fs_list_u32_t) { (uint32_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_io_streams_method_input_stream_read(wasi_io_streams_borrow_input_stream_t self, uint64_t len, wasi_io_streams_result_list_u8_stream_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_input_stream_read((self).__handle, (int64_t) (len), ptr);
  wasi_io_streams_result_list_u8_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (p2fs_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_input_stream_blocking_read(wasi_io_streams_borrow_input_stream_t self, uint64_t len, wasi_io_streams_result_list_u8_stream_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_input_stream_blocking_read((self).__handle, (int64_t) (len), ptr);
  wasi_io_streams_result_list_u8_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (p2fs_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_input_stream_skip(wasi_io_streams_borrow_input_stream_t self, uint64_t len, wasi_io_streams_result_u64_stream_error_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_input_stream_skip((self).__handle, (int64_t) (len), ptr);
  wasi_io_streams_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 8)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_input_stream_blocking_skip(wasi_io_streams_borrow_input_stream_t self, uint64_t len, wasi_io_streams_result_u64_stream_error_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_input_stream_blocking_skip((self).__handle, (int64_t) (len), ptr);
  wasi_io_streams_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 8)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

wasi_io_streams_own_pollable_t wasi_io_streams_method_input_stream_subscribe(wasi_io_streams_borrow_input_stream_t self) {
  int32_t ret = __wasm_import_wasi_io_streams_method_input_stream_subscribe((self).__handle);
  return (wasi_io_streams_own_pollable_t) { ret };
}

void wasi_io_streams_method_output_stream_check_write(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_result_u64_stream_error_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_check_write((self).__handle, ptr);
  wasi_io_streams_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 8)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_output_stream_write(wasi_io_streams_borrow_output_stream_t self, p2fs_list_u8_t *contents, wasi_io_streams_result_void_stream_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_write((self).__handle, (int32_t) (*contents).ptr, (int32_t) (*contents).len, ptr);
  wasi_io_streams_result_void_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_output_stream_blocking_write_and_flush(wasi_io_streams_borrow_output_stream_t self, p2fs_list_u8_t *contents, wasi_io_streams_result_void_stream_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_blocking_write_and_flush((self).__handle, (int32_t) (*contents).ptr, (int32_t) (*contents).len, ptr);
  wasi_io_streams_result_void_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_output_stream_flush(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_result_void_stream_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_flush((self).__handle, ptr);
  wasi_io_streams_result_void_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_output_stream_blocking_flush(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_result_void_stream_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_blocking_flush((self).__handle, ptr);
  wasi_io_streams_result_void_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

wasi_io_streams_own_pollable_t wasi_io_streams_method_output_stream_subscribe(wasi_io_streams_borrow_output_stream_t self) {
  int32_t ret = __wasm_import_wasi_io_streams_method_output_stream_subscribe((self).__handle);
  return (wasi_io_streams_own_pollable_t) { ret };
}

void wasi_io_streams_method_output_stream_write_zeroes(wasi_io_streams_borrow_output_stream_t self, uint64_t len, wasi_io_streams_result_void_stream_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_write_zeroes((self).__handle, (int64_t) (len), ptr);
  wasi_io_streams_result_void_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_output_stream_blocking_write_zeroes_and_flush(wasi_io_streams_borrow_output_stream_t self, uint64_t len, wasi_io_streams_result_void_stream_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_blocking_write_zeroes_and_flush((self).__handle, (int64_t) (len), ptr);
  wasi_io_streams_result_void_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 8)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_output_stream_splice(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_borrow_input_stream_t src, uint64_t len, wasi_io_streams_result_u64_stream_error_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_splice((self).__handle, (src).__handle, (int64_t) (len), ptr);
  wasi_io_streams_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 8)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_method_output_stream_blocking_splice(wasi_io_streams_borrow_output_stream_t self, wasi_io_streams_borrow_input_stream_t src, uint64_t len, wasi_io_streams_result_u64_stream_error_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_method_output_stream_blocking_splice((self).__handle, (src).__handle, (int64_t) (len), ptr);
  wasi_io_streams_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_io_streams_stream_error_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 8)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.last_operation_failed = (wasi_io_streams_own_error_t) { *((int32_t*) (ptr + 12)) };
          break;
        }
        case 1: {
          break;
        }
      }
      
      result.val.err = variant;
      break;
    }
  }
  *ret = result;
}

void wasi_clocks_wall_clock_now(wasi_clocks_wall_clock_datetime_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_clocks_wall_clock_now(ptr);
  *ret = (wasi_clocks_wall_clock_datetime_t) {
    (uint64_t) (*((int64_t*) (ptr + 0))),
    (uint32_t) (*((int32_t*) (ptr + 8))),
  };
}

void wasi_clocks_wall_clock_resolution(wasi_clocks_wall_clock_datetime_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_clocks_wall_clock_resolution(ptr);
  *ret = (wasi_clocks_wall_clock_datetime_t) {
    (uint64_t) (*((int64_t*) (ptr + 0))),
    (uint32_t) (*((int32_t*) (ptr + 8))),
  };
}

void wasi_filesystem_types_method_descriptor_read_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_result_own_input_stream_error_code_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_read_via_stream((self).__handle, (int64_t) (offset), ptr);
  wasi_filesystem_types_result_own_input_stream_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_filesystem_types_own_input_stream_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_write_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_result_own_output_stream_error_code_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_write_via_stream((self).__handle, (int64_t) (offset), ptr);
  wasi_filesystem_types_result_own_output_stream_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_filesystem_types_own_output_stream_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_append_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_own_output_stream_error_code_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_append_via_stream((self).__handle, ptr);
  wasi_filesystem_types_result_own_output_stream_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_filesystem_types_own_output_stream_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_advise(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_filesize_t length, wasi_filesystem_types_advice_t advice, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_advise((self).__handle, (int64_t) (offset), (int64_t) (length), (int32_t) advice, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_sync_data(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_sync_data((self).__handle, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_get_flags(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_descriptor_flags_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_get_flags((self).__handle, ptr);
  wasi_filesystem_types_result_descriptor_flags_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_get_type(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_descriptor_type_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_get_type((self).__handle, ptr);
  wasi_filesystem_types_result_descriptor_type_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_set_size(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t size, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_set_size((self).__handle, (int64_t) (size), ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_set_times(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_new_timestamp_t *data_access_timestamp, wasi_filesystem_types_new_timestamp_t *data_modification_timestamp, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t variant;
  int64_t variant2;
  int32_t variant3;
  switch ((int32_t) (*data_access_timestamp).tag) {
    case 0: {
      variant = 0;
      variant2 = 0;
      variant3 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant2 = 0;
      variant3 = 0;
      break;
    }
    case 2: {
      const wasi_filesystem_types_datetime_t *payload1 = &(*data_access_timestamp).val.timestamp;
      variant = 2;
      variant2 = (int64_t) ((*payload1).seconds);
      variant3 = (int32_t) ((*payload1).nanoseconds);
      break;
    }
  }
  int32_t variant7;
  int64_t variant8;
  int32_t variant9;
  switch ((int32_t) (*data_modification_timestamp).tag) {
    case 0: {
      variant7 = 0;
      variant8 = 0;
      variant9 = 0;
      break;
    }
    case 1: {
      variant7 = 1;
      variant8 = 0;
      variant9 = 0;
      break;
    }
    case 2: {
      const wasi_filesystem_types_datetime_t *payload6 = &(*data_modification_timestamp).val.timestamp;
      variant7 = 2;
      variant8 = (int64_t) ((*payload6).seconds);
      variant9 = (int32_t) ((*payload6).nanoseconds);
      break;
    }
  }
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_set_times((self).__handle, variant, variant2, variant3, variant7, variant8, variant9, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_read(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t length, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_result_tuple2_list_u8_bool_error_code_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_read((self).__handle, (int64_t) (length), (int64_t) (offset), ptr);
  wasi_filesystem_types_result_tuple2_list_u8_bool_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (p2fs_tuple2_list_u8_bool_t) {
        (p2fs_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        (int32_t) (*((uint8_t*) (ptr + 12))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_write(wasi_filesystem_types_borrow_descriptor_t self, p2fs_list_u8_t *buffer, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_result_filesize_error_code_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_write((self).__handle, (int32_t) (*buffer).ptr, (int32_t) (*buffer).len, (int64_t) (offset), ptr);
  wasi_filesystem_types_result_filesize_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 8)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_read_directory(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_own_directory_entry_stream_error_code_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_read_directory((self).__handle, ptr);
  wasi_filesystem_types_result_own_directory_entry_stream_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_filesystem_types_own_directory_entry_stream_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_sync(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_sync((self).__handle, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_create_directory_at(wasi_filesystem_types_borrow_descriptor_t self, p2fs_string_t *path, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_create_directory_at((self).__handle, (int32_t) (*path).ptr, (int32_t) (*path).len, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_stat(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_descriptor_stat_error_code_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[104];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_stat((self).__handle, ptr);
  wasi_filesystem_types_result_descriptor_stat_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      wasi_filesystem_types_option_datetime_t option;
      switch ((int32_t) (*((uint8_t*) (ptr + 32)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (wasi_clocks_wall_clock_datetime_t) {
            (uint64_t) (*((int64_t*) (ptr + 40))),
            (uint32_t) (*((int32_t*) (ptr + 48))),
          };
          break;
        }
      }
      wasi_filesystem_types_option_datetime_t option0;
      switch ((int32_t) (*((uint8_t*) (ptr + 56)))) {
        case 0: {
          option0.is_some = false;
          break;
        }
        case 1: {
          option0.is_some = true;
          option0.val = (wasi_clocks_wall_clock_datetime_t) {
            (uint64_t) (*((int64_t*) (ptr + 64))),
            (uint32_t) (*((int32_t*) (ptr + 72))),
          };
          break;
        }
      }
      wasi_filesystem_types_option_datetime_t option1;
      switch ((int32_t) (*((uint8_t*) (ptr + 80)))) {
        case 0: {
          option1.is_some = false;
          break;
        }
        case 1: {
          option1.is_some = true;
          option1.val = (wasi_clocks_wall_clock_datetime_t) {
            (uint64_t) (*((int64_t*) (ptr + 88))),
            (uint32_t) (*((int32_t*) (ptr + 96))),
          };
          break;
        }
      }
      
      result.val.ok = (wasi_filesystem_types_descriptor_stat_t) {
        (int32_t) (*((uint8_t*) (ptr + 8))),
        (uint64_t) (*((int64_t*) (ptr + 16))),
        (uint64_t) (*((int64_t*) (ptr + 24))),
        option,
        option0,
        option1,
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 8)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_stat_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, p2fs_string_t *path, wasi_filesystem_types_result_descriptor_stat_error_code_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[104];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_stat_at((self).__handle, path_flags, (int32_t) (*path).ptr, (int32_t) (*path).len, ptr);
  wasi_filesystem_types_result_descriptor_stat_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      wasi_filesystem_types_option_datetime_t option;
      switch ((int32_t) (*((uint8_t*) (ptr + 32)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (wasi_clocks_wall_clock_datetime_t) {
            (uint64_t) (*((int64_t*) (ptr + 40))),
            (uint32_t) (*((int32_t*) (ptr + 48))),
          };
          break;
        }
      }
      wasi_filesystem_types_option_datetime_t option0;
      switch ((int32_t) (*((uint8_t*) (ptr + 56)))) {
        case 0: {
          option0.is_some = false;
          break;
        }
        case 1: {
          option0.is_some = true;
          option0.val = (wasi_clocks_wall_clock_datetime_t) {
            (uint64_t) (*((int64_t*) (ptr + 64))),
            (uint32_t) (*((int32_t*) (ptr + 72))),
          };
          break;
        }
      }
      wasi_filesystem_types_option_datetime_t option1;
      switch ((int32_t) (*((uint8_t*) (ptr + 80)))) {
        case 0: {
          option1.is_some = false;
          break;
        }
        case 1: {
          option1.is_some = true;
          option1.val = (wasi_clocks_wall_clock_datetime_t) {
            (uint64_t) (*((int64_t*) (ptr + 88))),
            (uint32_t) (*((int32_t*) (ptr + 96))),
          };
          break;
        }
      }
      
      result.val.ok = (wasi_filesystem_types_descriptor_stat_t) {
        (int32_t) (*((uint8_t*) (ptr + 8))),
        (uint64_t) (*((int64_t*) (ptr + 16))),
        (uint64_t) (*((int64_t*) (ptr + 24))),
        option,
        option0,
        option1,
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 8)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_set_times_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, p2fs_string_t *path, wasi_filesystem_types_new_timestamp_t *data_access_timestamp, wasi_filesystem_types_new_timestamp_t *data_modification_timestamp, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t variant;
  int64_t variant2;
  int32_t variant3;
  switch ((int32_t) (*data_access_timestamp).tag) {
    case 0: {
      variant = 0;
      variant2 = 0;
      variant3 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant2 = 0;
      variant3 = 0;
      break;
    }
    case 2: {
      const wasi_filesystem_types_datetime_t *payload1 = &(*data_access_timestamp).val.timestamp;
      variant = 2;
      variant2 = (int64_t) ((*payload1).seconds);
      variant3 = (int32_t) ((*payload1).nanoseconds);
      break;
    }
  }
  int32_t variant7;
  int64_t variant8;
  int32_t variant9;
  switch ((int32_t) (*data_modification_timestamp).tag) {
    case 0: {
      variant7 = 0;
      variant8 = 0;
      variant9 = 0;
      break;
    }
    case 1: {
      variant7 = 1;
      variant8 = 0;
      variant9 = 0;
      break;
    }
    case 2: {
      const wasi_filesystem_types_datetime_t *payload6 = &(*data_modification_timestamp).val.timestamp;
      variant7 = 2;
      variant8 = (int64_t) ((*payload6).seconds);
      variant9 = (int32_t) ((*payload6).nanoseconds);
      break;
    }
  }
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_set_times_at((self).__handle, path_flags, (int32_t) (*path).ptr, (int32_t) (*path).len, variant, variant2, variant3, variant7, variant8, variant9, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_link_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t old_path_flags, p2fs_string_t *old_path, wasi_filesystem_types_borrow_descriptor_t new_descriptor, p2fs_string_t *new_path, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_link_at((self).__handle, old_path_flags, (int32_t) (*old_path).ptr, (int32_t) (*old_path).len, (new_descriptor).__handle, (int32_t) (*new_path).ptr, (int32_t) (*new_path).len, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_open_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, p2fs_string_t *path, wasi_filesystem_types_open_flags_t open_flags, wasi_filesystem_types_descriptor_flags_t flags, wasi_filesystem_types_result_own_descriptor_error_code_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_open_at((self).__handle, path_flags, (int32_t) (*path).ptr, (int32_t) (*path).len, open_flags, flags, ptr);
  wasi_filesystem_types_result_own_descriptor_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_filesystem_types_own_descriptor_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_readlink_at(wasi_filesystem_types_borrow_descriptor_t self, p2fs_string_t *path, wasi_filesystem_types_result_string_error_code_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_readlink_at((self).__handle, (int32_t) (*path).ptr, (int32_t) (*path).len, ptr);
  wasi_filesystem_types_result_string_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (p2fs_string_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_remove_directory_at(wasi_filesystem_types_borrow_descriptor_t self, p2fs_string_t *path, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_remove_directory_at((self).__handle, (int32_t) (*path).ptr, (int32_t) (*path).len, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_rename_at(wasi_filesystem_types_borrow_descriptor_t self, p2fs_string_t *old_path, wasi_filesystem_types_borrow_descriptor_t new_descriptor, p2fs_string_t *new_path, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_rename_at((self).__handle, (int32_t) (*old_path).ptr, (int32_t) (*old_path).len, (new_descriptor).__handle, (int32_t) (*new_path).ptr, (int32_t) (*new_path).len, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_symlink_at(wasi_filesystem_types_borrow_descriptor_t self, p2fs_string_t *old_path, p2fs_string_t *new_path, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_symlink_at((self).__handle, (int32_t) (*old_path).ptr, (int32_t) (*old_path).len, (int32_t) (*new_path).ptr, (int32_t) (*new_path).len, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_unlink_file_at(wasi_filesystem_types_borrow_descriptor_t self, p2fs_string_t *path, wasi_filesystem_types_result_void_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_unlink_file_at((self).__handle, (int32_t) (*path).ptr, (int32_t) (*path).len, ptr);
  wasi_filesystem_types_result_void_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = result;
}

bool wasi_filesystem_types_method_descriptor_is_same_object(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_borrow_descriptor_t other) {
  int32_t ret = __wasm_import_wasi_filesystem_types_method_descriptor_is_same_object((self).__handle, (other).__handle);
  return ret;
}

void wasi_filesystem_types_method_descriptor_metadata_hash(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_metadata_hash_value_error_code_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_metadata_hash((self).__handle, ptr);
  wasi_filesystem_types_result_metadata_hash_value_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_filesystem_types_metadata_hash_value_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (uint64_t) (*((int64_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 8)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_descriptor_metadata_hash_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, p2fs_string_t *path, wasi_filesystem_types_result_metadata_hash_value_error_code_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_descriptor_metadata_hash_at((self).__handle, path_flags, (int32_t) (*path).ptr, (int32_t) (*path).len, ptr);
  wasi_filesystem_types_result_metadata_hash_value_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_filesystem_types_metadata_hash_value_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (uint64_t) (*((int64_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 8)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_method_directory_entry_stream_read_directory_entry(wasi_filesystem_types_borrow_directory_entry_stream_t self, wasi_filesystem_types_result_option_directory_entry_error_code_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[20];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_method_directory_entry_stream_read_directory_entry((self).__handle, ptr);
  wasi_filesystem_types_result_option_directory_entry_error_code_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      wasi_filesystem_types_option_directory_entry_t option;
      switch ((int32_t) (*((uint8_t*) (ptr + 4)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (wasi_filesystem_types_directory_entry_t) {
            (int32_t) (*((uint8_t*) (ptr + 8))),
            (p2fs_string_t) { (uint8_t*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) },
          };
          break;
        }
      }
      
      result.val.ok = option;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) (*((uint8_t*) (ptr + 4)));
      break;
    }
  }
  *ret = result;
}

void wasi_filesystem_types_filesystem_error_code(wasi_filesystem_types_borrow_error_t err_, wasi_filesystem_types_option_error_code_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_filesystem_types_filesystem_error_code((err_).__handle, ptr);
  wasi_filesystem_types_option_error_code_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (int32_t) (*((uint8_t*) (ptr + 1)));
      break;
    }
  }
  *ret = option;
}

extern void __component_type_object_force_link_p2fs(void);
void __component_type_object_force_link_p2fs_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_p2fs();
}
