// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package stderr represents the interface "wasi:cli/stderr@0.2.0".
package stderr

import (
	"github.com/omnide/dc-wasm-go/ex/echo/wasi/wasi/io/v0.2.0/streams"
)

// OutputStream represents the resource "wasi:io/streams@0.2.0#output-stream".
//
// See [streams.OutputStream] for more information.
type OutputStream = streams.OutputStream

// GetStderr represents function "wasi:cli/stderr@0.2.0#get-stderr".
//
//	get-stderr: func() -> output-stream
//
//go:nosplit
func GetStderr() OutputStream {
	return wasmimport_GetStderr()
}

//go:wasmimport wasi:cli/stderr@0.2.0 get-stderr
//go:noescape
func wasmimport_GetStderr() OutputStream
