// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
#include "p2random.h"


__attribute__((__import_module__("wasi:random/random@0.2.0"), __import_name__("get-random-bytes")))
extern void __wasm_import_wasi_random_random_get_random_bytes(int64_t, int32_t);

__attribute__((__import_module__("wasi:random/random@0.2.0"), __import_name__("get-random-u64")))
extern int64_t __wasm_import_wasi_random_random_get_random_u64(void);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void p2random_list_u8_free(p2random_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

// Component Adapters

void wasi_random_random_get_random_bytes(uint64_t len, p2random_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_random_random_get_random_bytes((int64_t) (len), ptr);
  *ret = (p2random_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

uint64_t wasi_random_random_get_random_u64(void) {
  int64_t ret = __wasm_import_wasi_random_random_get_random_u64();
  return (uint64_t) (ret);
}

extern void __component_type_object_force_link_p2random(void);
void __component_type_object_force_link_p2random_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_p2random();
}
