#!/usr/bin/env bash
set -eEuo pipefail

# [wasi-io]: https://github.com/WebAssembly/wasi-io
# [wasi-clocks]: https://github.com/WebAssembly/wasi-clocks
# [wasi-random]: https://github.com/WebAssembly/wasi-random
# [wasi-filesystem]: https://github.com/WebAssembly/wasi-filesystem
# [wasi-sockets]: https://github.com/WebAssembly/wasi-sockets
# [wasi-cli]: https://github.com/WebAssembly/wasi-cli
# [wasi-http]: https://github.com/WebAssembly/wasi-http

TAG="v0.2.0"
WORLDS=(
  "wasi-io"
  "wasi-clocks"
  "wasi-random"
  "wasi-filesystem"
  "wasi-sockets"
  "wasi-cli"
  "wasi-http"
)

this_file=$(realpath "$0")
workspace=$(dirname "$(dirname "$(dirname $this_file)")")
mkdir -p "${workspace}/worlds"

for world in "${WORLDS[@]}"; do
    cd "${workspace}/worlds"
    if [ -d "$world" ]; then
        cd "$world"
        git switch main
        git pull
        git checkout "$TAG"
    else
        gh repo clone "WebAssembly/$world"
        cd "$world"
        git checkout "$TAG"
    fi
done

cd "${workspace}/wasm-tools-go"
for world in "${WORLDS[@]}"; do
    wit-bindgen-go generate ../worlds/$world/wit
done

