// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package types represents the interface "wasi:http/types@0.2.0".
//
// This interface defines all of the types and methods for implementing
// HTTP Requests and Responses, both incoming and outgoing, as well as
// their headers, trailers, and bodies.
package types

import (
	monotonicclock "github.com/omnide/dc-wasm-go/ex/echo/wasi/wasi/clocks/v0.2.0/monotonic-clock"
	ioerror "github.com/omnide/dc-wasm-go/ex/echo/wasi/wasi/io/v0.2.0/error"
	"github.com/omnide/dc-wasm-go/ex/echo/wasi/wasi/io/v0.2.0/poll"
	"github.com/omnide/dc-wasm-go/ex/echo/wasi/wasi/io/v0.2.0/streams"
	"github.com/ydnar/wasm-tools-go/cm"
)

// Duration represents the type "wasi:clocks/monotonic-clock@0.2.0#duration".
//
// See [monotonicclock.Duration] for more information.
type Duration = monotonicclock.Duration

// InputStream represents the resource "wasi:io/streams@0.2.0#input-stream".
//
// See [streams.InputStream] for more information.
type InputStream = streams.InputStream

// OutputStream represents the resource "wasi:io/streams@0.2.0#output-stream".
//
// See [streams.OutputStream] for more information.
type OutputStream = streams.OutputStream

// IOError represents the resource "wasi:io/error@0.2.0#error".
//
// See [ioerror.Error] for more information.
type IOError = ioerror.Error

// Pollable represents the resource "wasi:io/poll@0.2.0#pollable".
//
// See [poll.Pollable] for more information.
type Pollable = poll.Pollable

// Method represents the variant "wasi:http/types@0.2.0#method".
//
// This type corresponds to HTTP standard Methods.
//
//	variant method {
//		get,
//		head,
//		post,
//		put,
//		delete,
//		connect,
//		options,
//		trace,
//		patch,
//		other(string),
//	}
type Method cm.Variant[uint8, string, string]

// MethodGet returns a [Method] of case "get".
func MethodGet() Method {
	var data struct{}
	return cm.New[Method](0, data)
}

// Get returns true if [Method] represents the variant case "get".
func (self *Method) Get() bool {
	return cm.Tag(self) == 0
}

// MethodHead returns a [Method] of case "head".
func MethodHead() Method {
	var data struct{}
	return cm.New[Method](1, data)
}

// Head returns true if [Method] represents the variant case "head".
func (self *Method) Head() bool {
	return cm.Tag(self) == 1
}

// MethodPost returns a [Method] of case "post".
func MethodPost() Method {
	var data struct{}
	return cm.New[Method](2, data)
}

// Post returns true if [Method] represents the variant case "post".
func (self *Method) Post() bool {
	return cm.Tag(self) == 2
}

// MethodPut returns a [Method] of case "put".
func MethodPut() Method {
	var data struct{}
	return cm.New[Method](3, data)
}

// Put returns true if [Method] represents the variant case "put".
func (self *Method) Put() bool {
	return cm.Tag(self) == 3
}

// MethodDelete returns a [Method] of case "delete".
func MethodDelete() Method {
	var data struct{}
	return cm.New[Method](4, data)
}

// Delete returns true if [Method] represents the variant case "delete".
func (self *Method) Delete() bool {
	return cm.Tag(self) == 4
}

// MethodConnect returns a [Method] of case "connect".
func MethodConnect() Method {
	var data struct{}
	return cm.New[Method](5, data)
}

// Connect returns true if [Method] represents the variant case "connect".
func (self *Method) Connect() bool {
	return cm.Tag(self) == 5
}

// MethodOptions returns a [Method] of case "options".
func MethodOptions() Method {
	var data struct{}
	return cm.New[Method](6, data)
}

// Options returns true if [Method] represents the variant case "options".
func (self *Method) Options() bool {
	return cm.Tag(self) == 6
}

// MethodTrace returns a [Method] of case "trace".
func MethodTrace() Method {
	var data struct{}
	return cm.New[Method](7, data)
}

// Trace returns true if [Method] represents the variant case "trace".
func (self *Method) Trace() bool {
	return cm.Tag(self) == 7
}

// MethodPatch returns a [Method] of case "patch".
func MethodPatch() Method {
	var data struct{}
	return cm.New[Method](8, data)
}

// Patch returns true if [Method] represents the variant case "patch".
func (self *Method) Patch() bool {
	return cm.Tag(self) == 8
}

// MethodOther returns a [Method] of case "other".
func MethodOther(data string) Method {
	return cm.New[Method](9, data)
}

// Other returns a non-nil *[string] if [Method] represents the variant case "other".
func (self *Method) Other() *string {
	return cm.Case[string](self, 9)
}

// Scheme represents the variant "wasi:http/types@0.2.0#scheme".
//
// This type corresponds to HTTP standard Related Schemes.
//
//	variant scheme {
//		HTTP,
//		HTTPS,
//		other(string),
//	}
type Scheme cm.Variant[uint8, string, string]

// SchemeHTTP returns a [Scheme] of case "HTTP".
func SchemeHTTP() Scheme {
	var data struct{}
	return cm.New[Scheme](0, data)
}

// HTTP returns true if [Scheme] represents the variant case "HTTP".
func (self *Scheme) HTTP() bool {
	return cm.Tag(self) == 0
}

// SchemeHTTPS returns a [Scheme] of case "HTTPS".
func SchemeHTTPS() Scheme {
	var data struct{}
	return cm.New[Scheme](1, data)
}

// HTTPS returns true if [Scheme] represents the variant case "HTTPS".
func (self *Scheme) HTTPS() bool {
	return cm.Tag(self) == 1
}

// SchemeOther returns a [Scheme] of case "other".
func SchemeOther(data string) Scheme {
	return cm.New[Scheme](2, data)
}

// Other returns a non-nil *[string] if [Scheme] represents the variant case "other".
func (self *Scheme) Other() *string {
	return cm.Case[string](self, 2)
}

// DNSErrorPayload represents the record "wasi:http/types@0.2.0#DNS-error-payload".
//
// Defines the case payload type for `DNS-error` above:
//
//	record DNS-error-payload {
//		rcode: option<string>,
//		info-code: option<u16>,
//	}
type DNSErrorPayload struct {
	Rcode    cm.Option[string]
	InfoCode cm.Option[uint16]
}

// TLSAlertReceivedPayload represents the record "wasi:http/types@0.2.0#TLS-alert-received-payload".
//
// Defines the case payload type for `TLS-alert-received` above:
//
//	record TLS-alert-received-payload {
//		alert-id: option<u8>,
//		alert-message: option<string>,
//	}
type TLSAlertReceivedPayload struct {
	AlertID      cm.Option[uint8]
	AlertMessage cm.Option[string]
}

// FieldSizePayload represents the record "wasi:http/types@0.2.0#field-size-payload".
//
// Defines the case payload type for `HTTP-response-{header,trailer}-size` above:
//
//	record field-size-payload {
//		field-name: option<string>,
//		field-size: option<u32>,
//	}
type FieldSizePayload struct {
	FieldName cm.Option[string]
	FieldSize cm.Option[uint32]
}

// ErrorCode represents the variant "wasi:http/types@0.2.0#error-code".
//
// These cases are inspired by the IANA HTTP Proxy Error Types:
// https://www.iana.org/assignments/http-proxy-status/http-proxy-status.xhtml#table-http-proxy-error-types
//
//	variant error-code {
//		DNS-timeout,
//		DNS-error(DNS-error-payload),
//		destination-not-found,
//		destination-unavailable,
//		destination-IP-prohibited,
//		destination-IP-unroutable,
//		connection-refused,
//		connection-terminated,
//		connection-timeout,
//		connection-read-timeout,
//		connection-write-timeout,
//		connection-limit-reached,
//		TLS-protocol-error,
//		TLS-certificate-error,
//		TLS-alert-received(TLS-alert-received-payload),
//		HTTP-request-denied,
//		HTTP-request-length-required,
//		HTTP-request-body-size(option<u64>),
//		HTTP-request-method-invalid,
//		HTTP-request-URI-invalid,
//		HTTP-request-URI-too-long,
//		HTTP-request-header-section-size(option<u32>),
//		HTTP-request-header-size(option<field-size-payload>),
//		HTTP-request-trailer-section-size(option<u32>),
//		HTTP-request-trailer-size(field-size-payload),
//		HTTP-response-incomplete,
//		HTTP-response-header-section-size(option<u32>),
//		HTTP-response-header-size(field-size-payload),
//		HTTP-response-body-size(option<u64>),
//		HTTP-response-trailer-section-size(option<u32>),
//		HTTP-response-trailer-size(field-size-payload),
//		HTTP-response-transfer-coding(option<string>),
//		HTTP-response-content-coding(option<string>),
//		HTTP-response-timeout,
//		HTTP-upgrade-failed,
//		HTTP-protocol-error,
//		loop-detected,
//		configuration-error,
//		internal-error(option<string>),
//	}
type ErrorCode cm.Variant[uint8, cm.Option[FieldSizePayload], cm.Option[uint64]]

// ErrorCodeDNSTimeout returns a [ErrorCode] of case "DNS-timeout".
func ErrorCodeDNSTimeout() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](0, data)
}

// DNSTimeout returns true if [ErrorCode] represents the variant case "DNS-timeout".
func (self *ErrorCode) DNSTimeout() bool {
	return cm.Tag(self) == 0
}

// ErrorCodeDNSError returns a [ErrorCode] of case "DNS-error".
func ErrorCodeDNSError(data DNSErrorPayload) ErrorCode {
	return cm.New[ErrorCode](1, data)
}

// DNSError returns a non-nil *[DNSErrorPayload] if [ErrorCode] represents the variant case "DNS-error".
func (self *ErrorCode) DNSError() *DNSErrorPayload {
	return cm.Case[DNSErrorPayload](self, 1)
}

// ErrorCodeDestinationNotFound returns a [ErrorCode] of case "destination-not-found".
func ErrorCodeDestinationNotFound() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](2, data)
}

// DestinationNotFound returns true if [ErrorCode] represents the variant case "destination-not-found".
func (self *ErrorCode) DestinationNotFound() bool {
	return cm.Tag(self) == 2
}

// ErrorCodeDestinationUnavailable returns a [ErrorCode] of case "destination-unavailable".
func ErrorCodeDestinationUnavailable() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](3, data)
}

// DestinationUnavailable returns true if [ErrorCode] represents the variant case "destination-unavailable".
func (self *ErrorCode) DestinationUnavailable() bool {
	return cm.Tag(self) == 3
}

// ErrorCodeDestinationIPProhibited returns a [ErrorCode] of case "destination-IP-prohibited".
func ErrorCodeDestinationIPProhibited() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](4, data)
}

// DestinationIPProhibited returns true if [ErrorCode] represents the variant case "destination-IP-prohibited".
func (self *ErrorCode) DestinationIPProhibited() bool {
	return cm.Tag(self) == 4
}

// ErrorCodeDestinationIPUnroutable returns a [ErrorCode] of case "destination-IP-unroutable".
func ErrorCodeDestinationIPUnroutable() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](5, data)
}

// DestinationIPUnroutable returns true if [ErrorCode] represents the variant case "destination-IP-unroutable".
func (self *ErrorCode) DestinationIPUnroutable() bool {
	return cm.Tag(self) == 5
}

// ErrorCodeConnectionRefused returns a [ErrorCode] of case "connection-refused".
func ErrorCodeConnectionRefused() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](6, data)
}

// ConnectionRefused returns true if [ErrorCode] represents the variant case "connection-refused".
func (self *ErrorCode) ConnectionRefused() bool {
	return cm.Tag(self) == 6
}

// ErrorCodeConnectionTerminated returns a [ErrorCode] of case "connection-terminated".
func ErrorCodeConnectionTerminated() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](7, data)
}

// ConnectionTerminated returns true if [ErrorCode] represents the variant case "connection-terminated".
func (self *ErrorCode) ConnectionTerminated() bool {
	return cm.Tag(self) == 7
}

// ErrorCodeConnectionTimeout returns a [ErrorCode] of case "connection-timeout".
func ErrorCodeConnectionTimeout() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](8, data)
}

// ConnectionTimeout returns true if [ErrorCode] represents the variant case "connection-timeout".
func (self *ErrorCode) ConnectionTimeout() bool {
	return cm.Tag(self) == 8
}

// ErrorCodeConnectionReadTimeout returns a [ErrorCode] of case "connection-read-timeout".
func ErrorCodeConnectionReadTimeout() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](9, data)
}

// ConnectionReadTimeout returns true if [ErrorCode] represents the variant case "connection-read-timeout".
func (self *ErrorCode) ConnectionReadTimeout() bool {
	return cm.Tag(self) == 9
}

// ErrorCodeConnectionWriteTimeout returns a [ErrorCode] of case "connection-write-timeout".
func ErrorCodeConnectionWriteTimeout() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](10, data)
}

// ConnectionWriteTimeout returns true if [ErrorCode] represents the variant case "connection-write-timeout".
func (self *ErrorCode) ConnectionWriteTimeout() bool {
	return cm.Tag(self) == 10
}

// ErrorCodeConnectionLimitReached returns a [ErrorCode] of case "connection-limit-reached".
func ErrorCodeConnectionLimitReached() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](11, data)
}

// ConnectionLimitReached returns true if [ErrorCode] represents the variant case "connection-limit-reached".
func (self *ErrorCode) ConnectionLimitReached() bool {
	return cm.Tag(self) == 11
}

// ErrorCodeTLSProtocolError returns a [ErrorCode] of case "TLS-protocol-error".
func ErrorCodeTLSProtocolError() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](12, data)
}

// TLSProtocolError returns true if [ErrorCode] represents the variant case "TLS-protocol-error".
func (self *ErrorCode) TLSProtocolError() bool {
	return cm.Tag(self) == 12
}

// ErrorCodeTLSCertificateError returns a [ErrorCode] of case "TLS-certificate-error".
func ErrorCodeTLSCertificateError() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](13, data)
}

// TLSCertificateError returns true if [ErrorCode] represents the variant case "TLS-certificate-error".
func (self *ErrorCode) TLSCertificateError() bool {
	return cm.Tag(self) == 13
}

// ErrorCodeTLSAlertReceived returns a [ErrorCode] of case "TLS-alert-received".
func ErrorCodeTLSAlertReceived(data TLSAlertReceivedPayload) ErrorCode {
	return cm.New[ErrorCode](14, data)
}

// TLSAlertReceived returns a non-nil *[TLSAlertReceivedPayload] if [ErrorCode] represents the variant case "TLS-alert-received".
func (self *ErrorCode) TLSAlertReceived() *TLSAlertReceivedPayload {
	return cm.Case[TLSAlertReceivedPayload](self, 14)
}

// ErrorCodeHTTPRequestDenied returns a [ErrorCode] of case "HTTP-request-denied".
func ErrorCodeHTTPRequestDenied() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](15, data)
}

// HTTPRequestDenied returns true if [ErrorCode] represents the variant case "HTTP-request-denied".
func (self *ErrorCode) HTTPRequestDenied() bool {
	return cm.Tag(self) == 15
}

// ErrorCodeHTTPRequestLengthRequired returns a [ErrorCode] of case "HTTP-request-length-required".
func ErrorCodeHTTPRequestLengthRequired() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](16, data)
}

// HTTPRequestLengthRequired returns true if [ErrorCode] represents the variant case "HTTP-request-length-required".
func (self *ErrorCode) HTTPRequestLengthRequired() bool {
	return cm.Tag(self) == 16
}

// ErrorCodeHTTPRequestBodySize returns a [ErrorCode] of case "HTTP-request-body-size".
func ErrorCodeHTTPRequestBodySize(data cm.Option[uint64]) ErrorCode {
	return cm.New[ErrorCode](17, data)
}

// HTTPRequestBodySize returns a non-nil *[cm.Option[uint64]] if [ErrorCode] represents the variant case "HTTP-request-body-size".
func (self *ErrorCode) HTTPRequestBodySize() *cm.Option[uint64] {
	return cm.Case[cm.Option[uint64]](self, 17)
}

// ErrorCodeHTTPRequestMethodInvalid returns a [ErrorCode] of case "HTTP-request-method-invalid".
func ErrorCodeHTTPRequestMethodInvalid() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](18, data)
}

// HTTPRequestMethodInvalid returns true if [ErrorCode] represents the variant case "HTTP-request-method-invalid".
func (self *ErrorCode) HTTPRequestMethodInvalid() bool {
	return cm.Tag(self) == 18
}

// ErrorCodeHTTPRequestURIInvalid returns a [ErrorCode] of case "HTTP-request-URI-invalid".
func ErrorCodeHTTPRequestURIInvalid() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](19, data)
}

// HTTPRequestURIInvalid returns true if [ErrorCode] represents the variant case "HTTP-request-URI-invalid".
func (self *ErrorCode) HTTPRequestURIInvalid() bool {
	return cm.Tag(self) == 19
}

// ErrorCodeHTTPRequestURITooLong returns a [ErrorCode] of case "HTTP-request-URI-too-long".
func ErrorCodeHTTPRequestURITooLong() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](20, data)
}

// HTTPRequestURITooLong returns true if [ErrorCode] represents the variant case "HTTP-request-URI-too-long".
func (self *ErrorCode) HTTPRequestURITooLong() bool {
	return cm.Tag(self) == 20
}

// ErrorCodeHTTPRequestHeaderSectionSize returns a [ErrorCode] of case "HTTP-request-header-section-size".
func ErrorCodeHTTPRequestHeaderSectionSize(data cm.Option[uint32]) ErrorCode {
	return cm.New[ErrorCode](21, data)
}

// HTTPRequestHeaderSectionSize returns a non-nil *[cm.Option[uint32]] if [ErrorCode] represents the variant case "HTTP-request-header-section-size".
func (self *ErrorCode) HTTPRequestHeaderSectionSize() *cm.Option[uint32] {
	return cm.Case[cm.Option[uint32]](self, 21)
}

// ErrorCodeHTTPRequestHeaderSize returns a [ErrorCode] of case "HTTP-request-header-size".
func ErrorCodeHTTPRequestHeaderSize(data cm.Option[FieldSizePayload]) ErrorCode {
	return cm.New[ErrorCode](22, data)
}

// HTTPRequestHeaderSize returns a non-nil *[cm.Option[FieldSizePayload]] if [ErrorCode] represents the variant case "HTTP-request-header-size".
func (self *ErrorCode) HTTPRequestHeaderSize() *cm.Option[FieldSizePayload] {
	return cm.Case[cm.Option[FieldSizePayload]](self, 22)
}

// ErrorCodeHTTPRequestTrailerSectionSize returns a [ErrorCode] of case "HTTP-request-trailer-section-size".
func ErrorCodeHTTPRequestTrailerSectionSize(data cm.Option[uint32]) ErrorCode {
	return cm.New[ErrorCode](23, data)
}

// HTTPRequestTrailerSectionSize returns a non-nil *[cm.Option[uint32]] if [ErrorCode] represents the variant case "HTTP-request-trailer-section-size".
func (self *ErrorCode) HTTPRequestTrailerSectionSize() *cm.Option[uint32] {
	return cm.Case[cm.Option[uint32]](self, 23)
}

// ErrorCodeHTTPRequestTrailerSize returns a [ErrorCode] of case "HTTP-request-trailer-size".
func ErrorCodeHTTPRequestTrailerSize(data FieldSizePayload) ErrorCode {
	return cm.New[ErrorCode](24, data)
}

// HTTPRequestTrailerSize returns a non-nil *[FieldSizePayload] if [ErrorCode] represents the variant case "HTTP-request-trailer-size".
func (self *ErrorCode) HTTPRequestTrailerSize() *FieldSizePayload {
	return cm.Case[FieldSizePayload](self, 24)
}

// ErrorCodeHTTPResponseIncomplete returns a [ErrorCode] of case "HTTP-response-incomplete".
func ErrorCodeHTTPResponseIncomplete() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](25, data)
}

// HTTPResponseIncomplete returns true if [ErrorCode] represents the variant case "HTTP-response-incomplete".
func (self *ErrorCode) HTTPResponseIncomplete() bool {
	return cm.Tag(self) == 25
}

// ErrorCodeHTTPResponseHeaderSectionSize returns a [ErrorCode] of case "HTTP-response-header-section-size".
func ErrorCodeHTTPResponseHeaderSectionSize(data cm.Option[uint32]) ErrorCode {
	return cm.New[ErrorCode](26, data)
}

// HTTPResponseHeaderSectionSize returns a non-nil *[cm.Option[uint32]] if [ErrorCode] represents the variant case "HTTP-response-header-section-size".
func (self *ErrorCode) HTTPResponseHeaderSectionSize() *cm.Option[uint32] {
	return cm.Case[cm.Option[uint32]](self, 26)
}

// ErrorCodeHTTPResponseHeaderSize returns a [ErrorCode] of case "HTTP-response-header-size".
func ErrorCodeHTTPResponseHeaderSize(data FieldSizePayload) ErrorCode {
	return cm.New[ErrorCode](27, data)
}

// HTTPResponseHeaderSize returns a non-nil *[FieldSizePayload] if [ErrorCode] represents the variant case "HTTP-response-header-size".
func (self *ErrorCode) HTTPResponseHeaderSize() *FieldSizePayload {
	return cm.Case[FieldSizePayload](self, 27)
}

// ErrorCodeHTTPResponseBodySize returns a [ErrorCode] of case "HTTP-response-body-size".
func ErrorCodeHTTPResponseBodySize(data cm.Option[uint64]) ErrorCode {
	return cm.New[ErrorCode](28, data)
}

// HTTPResponseBodySize returns a non-nil *[cm.Option[uint64]] if [ErrorCode] represents the variant case "HTTP-response-body-size".
func (self *ErrorCode) HTTPResponseBodySize() *cm.Option[uint64] {
	return cm.Case[cm.Option[uint64]](self, 28)
}

// ErrorCodeHTTPResponseTrailerSectionSize returns a [ErrorCode] of case "HTTP-response-trailer-section-size".
func ErrorCodeHTTPResponseTrailerSectionSize(data cm.Option[uint32]) ErrorCode {
	return cm.New[ErrorCode](29, data)
}

// HTTPResponseTrailerSectionSize returns a non-nil *[cm.Option[uint32]] if [ErrorCode] represents the variant case "HTTP-response-trailer-section-size".
func (self *ErrorCode) HTTPResponseTrailerSectionSize() *cm.Option[uint32] {
	return cm.Case[cm.Option[uint32]](self, 29)
}

// ErrorCodeHTTPResponseTrailerSize returns a [ErrorCode] of case "HTTP-response-trailer-size".
func ErrorCodeHTTPResponseTrailerSize(data FieldSizePayload) ErrorCode {
	return cm.New[ErrorCode](30, data)
}

// HTTPResponseTrailerSize returns a non-nil *[FieldSizePayload] if [ErrorCode] represents the variant case "HTTP-response-trailer-size".
func (self *ErrorCode) HTTPResponseTrailerSize() *FieldSizePayload {
	return cm.Case[FieldSizePayload](self, 30)
}

// ErrorCodeHTTPResponseTransferCoding returns a [ErrorCode] of case "HTTP-response-transfer-coding".
func ErrorCodeHTTPResponseTransferCoding(data cm.Option[string]) ErrorCode {
	return cm.New[ErrorCode](31, data)
}

// HTTPResponseTransferCoding returns a non-nil *[cm.Option[string]] if [ErrorCode] represents the variant case "HTTP-response-transfer-coding".
func (self *ErrorCode) HTTPResponseTransferCoding() *cm.Option[string] {
	return cm.Case[cm.Option[string]](self, 31)
}

// ErrorCodeHTTPResponseContentCoding returns a [ErrorCode] of case "HTTP-response-content-coding".
func ErrorCodeHTTPResponseContentCoding(data cm.Option[string]) ErrorCode {
	return cm.New[ErrorCode](32, data)
}

// HTTPResponseContentCoding returns a non-nil *[cm.Option[string]] if [ErrorCode] represents the variant case "HTTP-response-content-coding".
func (self *ErrorCode) HTTPResponseContentCoding() *cm.Option[string] {
	return cm.Case[cm.Option[string]](self, 32)
}

// ErrorCodeHTTPResponseTimeout returns a [ErrorCode] of case "HTTP-response-timeout".
func ErrorCodeHTTPResponseTimeout() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](33, data)
}

// HTTPResponseTimeout returns true if [ErrorCode] represents the variant case "HTTP-response-timeout".
func (self *ErrorCode) HTTPResponseTimeout() bool {
	return cm.Tag(self) == 33
}

// ErrorCodeHTTPUpgradeFailed returns a [ErrorCode] of case "HTTP-upgrade-failed".
func ErrorCodeHTTPUpgradeFailed() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](34, data)
}

// HTTPUpgradeFailed returns true if [ErrorCode] represents the variant case "HTTP-upgrade-failed".
func (self *ErrorCode) HTTPUpgradeFailed() bool {
	return cm.Tag(self) == 34
}

// ErrorCodeHTTPProtocolError returns a [ErrorCode] of case "HTTP-protocol-error".
func ErrorCodeHTTPProtocolError() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](35, data)
}

// HTTPProtocolError returns true if [ErrorCode] represents the variant case "HTTP-protocol-error".
func (self *ErrorCode) HTTPProtocolError() bool {
	return cm.Tag(self) == 35
}

// ErrorCodeLoopDetected returns a [ErrorCode] of case "loop-detected".
func ErrorCodeLoopDetected() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](36, data)
}

// LoopDetected returns true if [ErrorCode] represents the variant case "loop-detected".
func (self *ErrorCode) LoopDetected() bool {
	return cm.Tag(self) == 36
}

// ErrorCodeConfigurationError returns a [ErrorCode] of case "configuration-error".
func ErrorCodeConfigurationError() ErrorCode {
	var data struct{}
	return cm.New[ErrorCode](37, data)
}

// ConfigurationError returns true if [ErrorCode] represents the variant case "configuration-error".
func (self *ErrorCode) ConfigurationError() bool {
	return cm.Tag(self) == 37
}

// ErrorCodeInternalError returns a [ErrorCode] of case "internal-error".
//
// This is a catch-all error for anything that doesn't fit cleanly into a
// more specific case. It also includes an optional string for an
// unstructured description of the error. Users should not depend on the
// string for diagnosing errors, as it's not required to be consistent
// between implementations.
func ErrorCodeInternalError(data cm.Option[string]) ErrorCode {
	return cm.New[ErrorCode](38, data)
}

// InternalError returns a non-nil *[cm.Option[string]] if [ErrorCode] represents the variant case "internal-error".
func (self *ErrorCode) InternalError() *cm.Option[string] {
	return cm.Case[cm.Option[string]](self, 38)
}

// HeaderError represents the variant "wasi:http/types@0.2.0#header-error".
//
// This type enumerates the different kinds of errors that may occur when
// setting or appending to a `fields` resource.
//
//	variant header-error {
//		invalid-syntax,
//		forbidden,
//		immutable,
//	}
type HeaderError uint8

const (
	// This error indicates that a `field-key` or `field-value` was
	// syntactically invalid when used with an operation that sets headers in a
	// `fields`.
	HeaderErrorInvalidSyntax HeaderError = iota

	// This error indicates that a forbidden `field-key` was used when trying
	// to set a header in a `fields`.
	HeaderErrorForbidden

	// This error indicates that the operation on the `fields` was not
	// permitted because the fields are immutable.
	HeaderErrorImmutable
)

// FieldKey represents the type "wasi:http/types@0.2.0#field-key".
//
// Field keys are always strings.
//
//	type field-key = string
type FieldKey string

// FieldValue represents the list "wasi:http/types@0.2.0#field-value".
//
// Field values should always be ASCII strings. However, in
// reality, HTTP implementations often have to interpret malformed values,
// so they are provided as a list of bytes.
//
//	type field-value = list<u8>
type FieldValue cm.List[uint8]

// Fields represents the resource "wasi:http/types@0.2.0#fields".
//
// This following block defines the `fields` resource which corresponds to
// HTTP standard Fields. Fields are a common representation used for both
// Headers and Trailers.
//
// A `fields` may be mutable or immutable. A `fields` created using the
// constructor, `from-list`, or `clone` will be mutable, but a `fields`
// resource given by other means (including, but not limited to,
// `incoming-request.headers`, `outgoing-request.headers`) might be be
// immutable. In an immutable fields, the `set`, `append`, and `delete`
// operations will fail with `header-error.immutable`.
//
//	resource fields
type Fields cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self Fields) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]fields
//go:noescape
func (self Fields) wasmimport_ResourceDrop()

// NewFields represents constructor "[constructor]fields".
//
// Construct an empty HTTP Fields.
//
// The resulting `fields` is mutable.
//
//	[constructor]fields()
//
//go:nosplit
func NewFields() Fields {
	return wasmimport_NewFields()
}

//go:wasmimport wasi:http/types@0.2.0 [constructor]fields
//go:noescape
func wasmimport_NewFields() Fields

// FieldsFromList represents static function "from-list".
//
// Construct an HTTP Fields.
//
// The resulting `fields` is mutable.
//
// The list represents each key-value pair in the Fields. Keys
// which have multiple values are represented by multiple entries in this
// list with the same key.
//
// The tuple is a pair of the field key, represented as a string, and
// Value, represented as a list of bytes.
//
// An error result will be returned if any `field-key` or `field-value` is
// syntactically invalid, or if a field is forbidden.
//
//	from-list: static func(entries: list<tuple<field-key, field-value>>) -> result<fields,
//	header-error>
//
//go:nosplit
func FieldsFromList(entries cm.List[cm.Tuple[FieldKey, FieldValue]]) cm.OKResult[Fields, HeaderError] {
	var result cm.OKResult[Fields, HeaderError]
	wasmimport_FieldsFromList(entries, &result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [static]fields.from-list
//go:noescape
func wasmimport_FieldsFromList(entries cm.List[cm.Tuple[FieldKey, FieldValue]], result *cm.OKResult[Fields, HeaderError])

// Append represents method "append".
//
// Append a value for a key. Does not change or delete any existing
// values for that key.
//
// Fails with `header-error.immutable` if the `fields` are immutable.
//
// Fails with `header-error.invalid-syntax` if the `field-key` or
// `field-value` are syntactically invalid.
//
//	append: func(name: field-key, value: field-value) -> result<_, header-error>
//
//go:nosplit
func (self Fields) Append(name FieldKey, value FieldValue) cm.ErrResult[struct{}, HeaderError] {
	var result cm.ErrResult[struct{}, HeaderError]
	self.wasmimport_Append(name, value, &result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]fields.append
//go:noescape
func (self Fields) wasmimport_Append(name FieldKey, value FieldValue, result *cm.ErrResult[struct{}, HeaderError])

// Clone represents method "clone".
//
// Make a deep copy of the Fields. Equivelant in behavior to calling the
// `fields` constructor on the return value of `entries`. The resulting
// `fields` is mutable.
//
//	clone: func() -> fields
//
//go:nosplit
func (self Fields) Clone() Fields {
	return self.wasmimport_Clone()
}

//go:wasmimport wasi:http/types@0.2.0 [method]fields.clone
//go:noescape
func (self Fields) wasmimport_Clone() Fields

// Delete represents method "delete".
//
// Delete all values for a key. Does nothing if no values for the key
// exist.
//
// Fails with `header-error.immutable` if the `fields` are immutable.
//
// Fails with `header-error.invalid-syntax` if the `field-key` is
// syntactically invalid.
//
//	delete: func(name: field-key) -> result<_, header-error>
//
//go:nosplit
func (self Fields) Delete(name FieldKey) cm.ErrResult[struct{}, HeaderError] {
	var result cm.ErrResult[struct{}, HeaderError]
	self.wasmimport_Delete(name, &result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]fields.delete
//go:noescape
func (self Fields) wasmimport_Delete(name FieldKey, result *cm.ErrResult[struct{}, HeaderError])

// Entries represents method "entries".
//
// Retrieve the full set of keys and values in the Fields. Like the
// constructor, the list represents each key-value pair.
//
// The outer list represents each key-value pair in the Fields. Keys
// which have multiple values are represented by multiple entries in this
// list with the same key.
//
//	entries: func() -> list<tuple<field-key, field-value>>
//
//go:nosplit
func (self Fields) Entries() cm.List[cm.Tuple[FieldKey, FieldValue]] {
	var result cm.List[cm.Tuple[FieldKey, FieldValue]]
	self.wasmimport_Entries(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]fields.entries
//go:noescape
func (self Fields) wasmimport_Entries(result *cm.List[cm.Tuple[FieldKey, FieldValue]])

// Get represents method "get".
//
// Get all of the values corresponding to a key. If the key is not present
// in this `fields` or is syntactically invalid, an empty list is returned.
// However, if the key is present but empty, this is represented by a list
// with one or more empty field-values present.
//
//	get: func(name: field-key) -> list<field-value>
//
//go:nosplit
func (self Fields) Get(name FieldKey) cm.List[FieldValue] {
	var result cm.List[FieldValue]
	self.wasmimport_Get(name, &result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]fields.get
//go:noescape
func (self Fields) wasmimport_Get(name FieldKey, result *cm.List[FieldValue])

// Has represents method "has".
//
// Returns `true` when the key is present in this `fields`. If the key is
// syntactically invalid, `false` is returned.
//
//	has: func(name: field-key) -> bool
//
//go:nosplit
func (self Fields) Has(name FieldKey) bool {
	return self.wasmimport_Has(name)
}

//go:wasmimport wasi:http/types@0.2.0 [method]fields.has
//go:noescape
func (self Fields) wasmimport_Has(name FieldKey) bool

// Set represents method "set".
//
// Set all of the values for a key. Clears any existing values for that
// key, if they have been set.
//
// Fails with `header-error.immutable` if the `fields` are immutable.
//
// Fails with `header-error.invalid-syntax` if the `field-key` or any of
// the `field-value`s are syntactically invalid.
//
//	set: func(name: field-key, value: list<field-value>) -> result<_, header-error>
//
//go:nosplit
func (self Fields) Set(name FieldKey, value cm.List[FieldValue]) cm.ErrResult[struct{}, HeaderError] {
	var result cm.ErrResult[struct{}, HeaderError]
	self.wasmimport_Set(name, value, &result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]fields.set
//go:noescape
func (self Fields) wasmimport_Set(name FieldKey, value cm.List[FieldValue], result *cm.ErrResult[struct{}, HeaderError])

// Headers represents the resource "wasi:http/types@0.2.0#fields".
//
// See [Fields] for more information.
type Headers = Fields

// Trailers represents the resource "wasi:http/types@0.2.0#fields".
//
// See [Fields] for more information.
type Trailers = Fields

// IncomingRequest represents the resource "wasi:http/types@0.2.0#incoming-request".
//
// Represents an incoming HTTP Request.
//
//	resource incoming-request
type IncomingRequest cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self IncomingRequest) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]incoming-request
//go:noescape
func (self IncomingRequest) wasmimport_ResourceDrop()

// Authority represents method "authority".
//
// Returns the authority from the request, if it was present.
//
//	authority: func() -> option<string>
//
//go:nosplit
func (self IncomingRequest) Authority() cm.Option[string] {
	var result cm.Option[string]
	self.wasmimport_Authority(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-request.authority
//go:noescape
func (self IncomingRequest) wasmimport_Authority(result *cm.Option[string])

// Consume represents method "consume".
//
// Gives the `incoming-body` associated with this request. Will only
// return success at most once, and subsequent calls will return error.
//
//	consume: func() -> result<incoming-body>
//
//go:nosplit
func (self IncomingRequest) Consume() cm.OKResult[IncomingBody, struct{}] {
	var result cm.OKResult[IncomingBody, struct{}]
	self.wasmimport_Consume(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-request.consume
//go:noescape
func (self IncomingRequest) wasmimport_Consume(result *cm.OKResult[IncomingBody, struct{}])

// Headers represents method "headers".
//
// Get the `headers` associated with the request.
//
// The returned `headers` resource is immutable: `set`, `append`, and
// `delete` operations will fail with `header-error.immutable`.
//
// The `headers` returned are a child resource: it must be dropped before
// the parent `incoming-request` is dropped. Dropping this
// `incoming-request` before all children are dropped will trap.
//
//	headers: func() -> headers
//
//go:nosplit
func (self IncomingRequest) Headers() Headers {
	return self.wasmimport_Headers()
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-request.headers
//go:noescape
func (self IncomingRequest) wasmimport_Headers() Headers

// Method represents method "method".
//
// Returns the method of the incoming request.
//
//	method: func() -> method
//
//go:nosplit
func (self IncomingRequest) Method() Method {
	var result Method
	self.wasmimport_Method(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-request.method
//go:noescape
func (self IncomingRequest) wasmimport_Method(result *Method)

// PathWithQuery represents method "path-with-query".
//
// Returns the path with query parameters from the request, as a string.
//
//	path-with-query: func() -> option<string>
//
//go:nosplit
func (self IncomingRequest) PathWithQuery() cm.Option[string] {
	var result cm.Option[string]
	self.wasmimport_PathWithQuery(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-request.path-with-query
//go:noescape
func (self IncomingRequest) wasmimport_PathWithQuery(result *cm.Option[string])

// Scheme represents method "scheme".
//
// Returns the protocol scheme from the request.
//
//	scheme: func() -> option<scheme>
//
//go:nosplit
func (self IncomingRequest) Scheme() cm.Option[Scheme] {
	var result cm.Option[Scheme]
	self.wasmimport_Scheme(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-request.scheme
//go:noescape
func (self IncomingRequest) wasmimport_Scheme(result *cm.Option[Scheme])

// OutgoingRequest represents the resource "wasi:http/types@0.2.0#outgoing-request".
//
// Represents an outgoing HTTP Request.
//
//	resource outgoing-request
type OutgoingRequest cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self OutgoingRequest) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]outgoing-request
//go:noescape
func (self OutgoingRequest) wasmimport_ResourceDrop()

// NewOutgoingRequest represents constructor "[constructor]outgoing-request".
//
// Construct a new `outgoing-request` with a default `method` of `GET`, and
// `none` values for `path-with-query`, `scheme`, and `authority`.
//
// * `headers` is the HTTP Headers for the Request.
//
// It is possible to construct, or manipulate with the accessor functions
// below, an `outgoing-request` with an invalid combination of `scheme`
// and `authority`, or `headers` which are not permitted to be sent.
// It is the obligation of the `outgoing-handler.handle` implementation
// to reject invalid constructions of `outgoing-request`.
//
//	[constructor]outgoing-request(headers: headers)
//
//go:nosplit
func NewOutgoingRequest(headers Headers) OutgoingRequest {
	return wasmimport_NewOutgoingRequest(headers)
}

//go:wasmimport wasi:http/types@0.2.0 [constructor]outgoing-request
//go:noescape
func wasmimport_NewOutgoingRequest(headers Headers) OutgoingRequest

// Authority represents method "authority".
//
// Get the HTTP Authority for the Request. A value of `none` may be used
// with Related Schemes which do not require an Authority. The HTTP and
// HTTPS schemes always require an authority.
//
//	authority: func() -> option<string>
//
//go:nosplit
func (self OutgoingRequest) Authority() cm.Option[string] {
	var result cm.Option[string]
	self.wasmimport_Authority(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.authority
//go:noescape
func (self OutgoingRequest) wasmimport_Authority(result *cm.Option[string])

// Body represents method "body".
//
// Returns the resource corresponding to the outgoing Body for this
// Request.
//
// Returns success on the first call: the `outgoing-body` resource for
// this `outgoing-request` can be retrieved at most once. Subsequent
// calls will return error.
//
//	body: func() -> result<outgoing-body>
//
//go:nosplit
func (self OutgoingRequest) Body() cm.OKResult[OutgoingBody, struct{}] {
	var result cm.OKResult[OutgoingBody, struct{}]
	self.wasmimport_Body(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.body
//go:noescape
func (self OutgoingRequest) wasmimport_Body(result *cm.OKResult[OutgoingBody, struct{}])

// Headers represents method "headers".
//
// Get the headers associated with the Request.
//
// The returned `headers` resource is immutable: `set`, `append`, and
// `delete` operations will fail with `header-error.immutable`.
//
// This headers resource is a child: it must be dropped before the parent
// `outgoing-request` is dropped, or its ownership is transfered to
// another component by e.g. `outgoing-handler.handle`.
//
//	headers: func() -> headers
//
//go:nosplit
func (self OutgoingRequest) Headers() Headers {
	return self.wasmimport_Headers()
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.headers
//go:noescape
func (self OutgoingRequest) wasmimport_Headers() Headers

// Method represents method "method".
//
// Get the Method for the Request.
//
//	method: func() -> method
//
//go:nosplit
func (self OutgoingRequest) Method() Method {
	var result Method
	self.wasmimport_Method(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.method
//go:noescape
func (self OutgoingRequest) wasmimport_Method(result *Method)

// PathWithQuery represents method "path-with-query".
//
// Get the combination of the HTTP Path and Query for the Request.
// When `none`, this represents an empty Path and empty Query.
//
//	path-with-query: func() -> option<string>
//
//go:nosplit
func (self OutgoingRequest) PathWithQuery() cm.Option[string] {
	var result cm.Option[string]
	self.wasmimport_PathWithQuery(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.path-with-query
//go:noescape
func (self OutgoingRequest) wasmimport_PathWithQuery(result *cm.Option[string])

// Scheme represents method "scheme".
//
// Get the HTTP Related Scheme for the Request. When `none`, the
// implementation may choose an appropriate default scheme.
//
//	scheme: func() -> option<scheme>
//
//go:nosplit
func (self OutgoingRequest) Scheme() cm.Option[Scheme] {
	var result cm.Option[Scheme]
	self.wasmimport_Scheme(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.scheme
//go:noescape
func (self OutgoingRequest) wasmimport_Scheme(result *cm.Option[Scheme])

// SetAuthority represents method "set-authority".
//
// Set the HTTP Authority for the Request. A value of `none` may be used
// with Related Schemes which do not require an Authority. The HTTP and
// HTTPS schemes always require an authority. Fails if the string given is
// not a syntactically valid uri authority.
//
//	set-authority: func(authority: option<string>) -> result
//
//go:nosplit
func (self OutgoingRequest) SetAuthority(authority cm.Option[string]) cm.Result {
	return self.wasmimport_SetAuthority(authority)
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.set-authority
//go:noescape
func (self OutgoingRequest) wasmimport_SetAuthority(authority cm.Option[string]) cm.Result

// SetMethod represents method "set-method".
//
// Set the Method for the Request. Fails if the string present in a
// `method.other` argument is not a syntactically valid method.
//
//	set-method: func(method: method) -> result
//
//go:nosplit
func (self OutgoingRequest) SetMethod(method Method) cm.Result {
	return self.wasmimport_SetMethod(method)
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.set-method
//go:noescape
func (self OutgoingRequest) wasmimport_SetMethod(method Method) cm.Result

// SetPathWithQuery represents method "set-path-with-query".
//
// Set the combination of the HTTP Path and Query for the Request.
// When `none`, this represents an empty Path and empty Query. Fails is the
// string given is not a syntactically valid path and query uri component.
//
//	set-path-with-query: func(path-with-query: option<string>) -> result
//
//go:nosplit
func (self OutgoingRequest) SetPathWithQuery(pathWithQuery cm.Option[string]) cm.Result {
	return self.wasmimport_SetPathWithQuery(pathWithQuery)
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.set-path-with-query
//go:noescape
func (self OutgoingRequest) wasmimport_SetPathWithQuery(pathWithQuery cm.Option[string]) cm.Result

// SetScheme represents method "set-scheme".
//
// Set the HTTP Related Scheme for the Request. When `none`, the
// implementation may choose an appropriate default scheme. Fails if the
// string given is not a syntactically valid uri scheme.
//
//	set-scheme: func(scheme: option<scheme>) -> result
//
//go:nosplit
func (self OutgoingRequest) SetScheme(scheme cm.Option[Scheme]) cm.Result {
	return self.wasmimport_SetScheme(scheme)
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-request.set-scheme
//go:noescape
func (self OutgoingRequest) wasmimport_SetScheme(scheme cm.Option[Scheme]) cm.Result

// RequestOptions represents the resource "wasi:http/types@0.2.0#request-options".
//
// Parameters for making an HTTP Request. Each of these parameters is
// currently an optional timeout applicable to the transport layer of the
// HTTP protocol.
//
// These timeouts are separate from any the user may use to bound a
// blocking call to `wasi:io/poll.poll`.
//
//	resource request-options
type RequestOptions cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self RequestOptions) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]request-options
//go:noescape
func (self RequestOptions) wasmimport_ResourceDrop()

// NewRequestOptions represents constructor "[constructor]request-options".
//
// Construct a default `request-options` value.
//
//	[constructor]request-options()
//
//go:nosplit
func NewRequestOptions() RequestOptions {
	return wasmimport_NewRequestOptions()
}

//go:wasmimport wasi:http/types@0.2.0 [constructor]request-options
//go:noescape
func wasmimport_NewRequestOptions() RequestOptions

// BetweenBytesTimeout represents method "between-bytes-timeout".
//
// The timeout for receiving subsequent chunks of bytes in the Response
// body stream.
//
//	between-bytes-timeout: func() -> option<duration>
//
//go:nosplit
func (self RequestOptions) BetweenBytesTimeout() cm.Option[Duration] {
	var result cm.Option[Duration]
	self.wasmimport_BetweenBytesTimeout(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]request-options.between-bytes-timeout
//go:noescape
func (self RequestOptions) wasmimport_BetweenBytesTimeout(result *cm.Option[Duration])

// ConnectTimeout represents method "connect-timeout".
//
// The timeout for the initial connect to the HTTP Server.
//
//	connect-timeout: func() -> option<duration>
//
//go:nosplit
func (self RequestOptions) ConnectTimeout() cm.Option[Duration] {
	var result cm.Option[Duration]
	self.wasmimport_ConnectTimeout(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]request-options.connect-timeout
//go:noescape
func (self RequestOptions) wasmimport_ConnectTimeout(result *cm.Option[Duration])

// FirstByteTimeout represents method "first-byte-timeout".
//
// The timeout for receiving the first byte of the Response body.
//
//	first-byte-timeout: func() -> option<duration>
//
//go:nosplit
func (self RequestOptions) FirstByteTimeout() cm.Option[Duration] {
	var result cm.Option[Duration]
	self.wasmimport_FirstByteTimeout(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]request-options.first-byte-timeout
//go:noescape
func (self RequestOptions) wasmimport_FirstByteTimeout(result *cm.Option[Duration])

// SetBetweenBytesTimeout represents method "set-between-bytes-timeout".
//
// Set the timeout for receiving subsequent chunks of bytes in the Response
// body stream. An error return value indicates that this timeout is not
// supported.
//
//	set-between-bytes-timeout: func(duration: option<duration>) -> result
//
//go:nosplit
func (self RequestOptions) SetBetweenBytesTimeout(duration cm.Option[Duration]) cm.Result {
	return self.wasmimport_SetBetweenBytesTimeout(duration)
}

//go:wasmimport wasi:http/types@0.2.0 [method]request-options.set-between-bytes-timeout
//go:noescape
func (self RequestOptions) wasmimport_SetBetweenBytesTimeout(duration cm.Option[Duration]) cm.Result

// SetConnectTimeout represents method "set-connect-timeout".
//
// Set the timeout for the initial connect to the HTTP Server. An error
// return value indicates that this timeout is not supported.
//
//	set-connect-timeout: func(duration: option<duration>) -> result
//
//go:nosplit
func (self RequestOptions) SetConnectTimeout(duration cm.Option[Duration]) cm.Result {
	return self.wasmimport_SetConnectTimeout(duration)
}

//go:wasmimport wasi:http/types@0.2.0 [method]request-options.set-connect-timeout
//go:noescape
func (self RequestOptions) wasmimport_SetConnectTimeout(duration cm.Option[Duration]) cm.Result

// SetFirstByteTimeout represents method "set-first-byte-timeout".
//
// Set the timeout for receiving the first byte of the Response body. An
// error return value indicates that this timeout is not supported.
//
//	set-first-byte-timeout: func(duration: option<duration>) -> result
//
//go:nosplit
func (self RequestOptions) SetFirstByteTimeout(duration cm.Option[Duration]) cm.Result {
	return self.wasmimport_SetFirstByteTimeout(duration)
}

//go:wasmimport wasi:http/types@0.2.0 [method]request-options.set-first-byte-timeout
//go:noescape
func (self RequestOptions) wasmimport_SetFirstByteTimeout(duration cm.Option[Duration]) cm.Result

// ResponseOutparam represents the resource "wasi:http/types@0.2.0#response-outparam".
//
// Represents the ability to send an HTTP Response.
//
// This resource is used by the `wasi:http/incoming-handler` interface to
// allow a Response to be sent corresponding to the Request provided as the
// other argument to `incoming-handler.handle`.
//
//	resource response-outparam
type ResponseOutparam cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self ResponseOutparam) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]response-outparam
//go:noescape
func (self ResponseOutparam) wasmimport_ResourceDrop()

// ResponseOutparamSet represents static function "set".
//
// Set the value of the `response-outparam` to either send a response,
// or indicate an error.
//
// This method consumes the `response-outparam` to ensure that it is
// called at most once. If it is never called, the implementation
// will respond with an error.
//
// The user may provide an `error` to `response` to allow the
// implementation determine how to respond with an HTTP error response.
//
//	set: static func(param: response-outparam, response: result<outgoing-response,
//	error-code>)
//
//go:nosplit
func ResponseOutparamSet(param ResponseOutparam, response cm.ErrResult[OutgoingResponse, ErrorCode]) {
	wasmimport_ResponseOutparamSet(param, response)
}

//go:wasmimport wasi:http/types@0.2.0 [static]response-outparam.set
//go:noescape
func wasmimport_ResponseOutparamSet(param ResponseOutparam, response cm.ErrResult[OutgoingResponse, ErrorCode])

// StatusCode represents the type "wasi:http/types@0.2.0#status-code".
//
// This type corresponds to the HTTP standard Status Code.
//
//	type status-code = u16
type StatusCode uint16

// IncomingResponse represents the resource "wasi:http/types@0.2.0#incoming-response".
//
// Represents an incoming HTTP Response.
//
//	resource incoming-response
type IncomingResponse cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self IncomingResponse) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]incoming-response
//go:noescape
func (self IncomingResponse) wasmimport_ResourceDrop()

// Consume represents method "consume".
//
// Returns the incoming body. May be called at most once. Returns error
// if called additional times.
//
//	consume: func() -> result<incoming-body>
//
//go:nosplit
func (self IncomingResponse) Consume() cm.OKResult[IncomingBody, struct{}] {
	var result cm.OKResult[IncomingBody, struct{}]
	self.wasmimport_Consume(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-response.consume
//go:noescape
func (self IncomingResponse) wasmimport_Consume(result *cm.OKResult[IncomingBody, struct{}])

// Headers represents method "headers".
//
// Returns the headers from the incoming response.
//
// The returned `headers` resource is immutable: `set`, `append`, and
// `delete` operations will fail with `header-error.immutable`.
//
// This headers resource is a child: it must be dropped before the parent
// `incoming-response` is dropped.
//
//	headers: func() -> headers
//
//go:nosplit
func (self IncomingResponse) Headers() Headers {
	return self.wasmimport_Headers()
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-response.headers
//go:noescape
func (self IncomingResponse) wasmimport_Headers() Headers

// Status represents method "status".
//
// Returns the status code from the incoming response.
//
//	status: func() -> status-code
//
//go:nosplit
func (self IncomingResponse) Status() StatusCode {
	return self.wasmimport_Status()
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-response.status
//go:noescape
func (self IncomingResponse) wasmimport_Status() StatusCode

// IncomingBody represents the resource "wasi:http/types@0.2.0#incoming-body".
//
// Represents an incoming HTTP Request or Response's Body.
//
// A body has both its contents - a stream of bytes - and a (possibly
// empty) set of trailers, indicating that the full contents of the
// body have been received. This resource represents the contents as
// an `input-stream` and the delivery of trailers as a `future-trailers`,
// and ensures that the user of this interface may only be consuming either
// the body contents or waiting on trailers at any given time.
//
//	resource incoming-body
type IncomingBody cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self IncomingBody) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]incoming-body
//go:noescape
func (self IncomingBody) wasmimport_ResourceDrop()

// IncomingBodyFinish represents static function "finish".
//
// Takes ownership of `incoming-body`, and returns a `future-trailers`.
// This function will trap if the `input-stream` child is still alive.
//
//	finish: static func(this: incoming-body) -> future-trailers
//
//go:nosplit
func IncomingBodyFinish(this IncomingBody) FutureTrailers {
	return wasmimport_IncomingBodyFinish(this)
}

//go:wasmimport wasi:http/types@0.2.0 [static]incoming-body.finish
//go:noescape
func wasmimport_IncomingBodyFinish(this IncomingBody) FutureTrailers

// Stream represents method "stream".
//
// Returns the contents of the body, as a stream of bytes.
//
// Returns success on first call: the stream representing the contents
// can be retrieved at most once. Subsequent calls will return error.
//
// The returned `input-stream` resource is a child: it must be dropped
// before the parent `incoming-body` is dropped, or consumed by
// `incoming-body.finish`.
//
// This invariant ensures that the implementation can determine whether
// the user is consuming the contents of the body, waiting on the
// `future-trailers` to be ready, or neither. This allows for network
// backpressure is to be applied when the user is consuming the body,
// and for that backpressure to not inhibit delivery of the trailers if
// the user does not read the entire body.
//
//	stream: func() -> result<input-stream>
//
//go:nosplit
func (self IncomingBody) Stream() cm.OKResult[InputStream, struct{}] {
	var result cm.OKResult[InputStream, struct{}]
	self.wasmimport_Stream(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]incoming-body.stream
//go:noescape
func (self IncomingBody) wasmimport_Stream(result *cm.OKResult[InputStream, struct{}])

// FutureTrailers represents the resource "wasi:http/types@0.2.0#future-trailers".
//
// Represents a future which may eventaully return trailers, or an error.
//
// In the case that the incoming HTTP Request or Response did not have any
// trailers, this future will resolve to the empty set of trailers once the
// complete Request or Response body has been received.
//
//	resource future-trailers
type FutureTrailers cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self FutureTrailers) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]future-trailers
//go:noescape
func (self FutureTrailers) wasmimport_ResourceDrop()

// Get represents method "get".
//
// Returns the contents of the trailers, or an error which occured,
// once the future is ready.
//
// The outer `option` represents future readiness. Users can wait on this
// `option` to become `some` using the `subscribe` method.
//
// The outer `result` is used to retrieve the trailers or error at most
// once. It will be success on the first call in which the outer option
// is `some`, and error on subsequent calls.
//
// The inner `result` represents that either the HTTP Request or Response
// body, as well as any trailers, were received successfully, or that an
// error occured receiving them. The optional `trailers` indicates whether
// or not trailers were present in the body.
//
// When some `trailers` are returned by this method, the `trailers`
// resource is immutable, and a child. Use of the `set`, `append`, or
// `delete` methods will return an error, and the resource must be
// dropped before the parent `future-trailers` is dropped.
//
//	get: func() -> option<result<result<option<trailers>, error-code>>>
//
//go:nosplit
func (self FutureTrailers) Get() cm.Option[cm.OKResult[cm.ErrResult[cm.Option[Trailers], ErrorCode], struct{}]] {
	var result cm.Option[cm.OKResult[cm.ErrResult[cm.Option[Trailers], ErrorCode], struct{}]]
	self.wasmimport_Get(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]future-trailers.get
//go:noescape
func (self FutureTrailers) wasmimport_Get(result *cm.Option[cm.OKResult[cm.ErrResult[cm.Option[Trailers], ErrorCode], struct{}]])

// Subscribe represents method "subscribe".
//
// Returns a pollable which becomes ready when either the trailers have
// been received, or an error has occured. When this pollable is ready,
// the `get` method will return `some`.
//
//	subscribe: func() -> pollable
//
//go:nosplit
func (self FutureTrailers) Subscribe() Pollable {
	return self.wasmimport_Subscribe()
}

//go:wasmimport wasi:http/types@0.2.0 [method]future-trailers.subscribe
//go:noescape
func (self FutureTrailers) wasmimport_Subscribe() Pollable

// OutgoingResponse represents the resource "wasi:http/types@0.2.0#outgoing-response".
//
// Represents an outgoing HTTP Response.
//
//	resource outgoing-response
type OutgoingResponse cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self OutgoingResponse) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]outgoing-response
//go:noescape
func (self OutgoingResponse) wasmimport_ResourceDrop()

// NewOutgoingResponse represents constructor "[constructor]outgoing-response".
//
// Construct an `outgoing-response`, with a default `status-code` of `200`.
// If a different `status-code` is needed, it must be set via the
// `set-status-code` method.
//
// * `headers` is the HTTP Headers for the Response.
//
//	[constructor]outgoing-response(headers: headers)
//
//go:nosplit
func NewOutgoingResponse(headers Headers) OutgoingResponse {
	return wasmimport_NewOutgoingResponse(headers)
}

//go:wasmimport wasi:http/types@0.2.0 [constructor]outgoing-response
//go:noescape
func wasmimport_NewOutgoingResponse(headers Headers) OutgoingResponse

// Body represents method "body".
//
// Returns the resource corresponding to the outgoing Body for this Response.
//
// Returns success on the first call: the `outgoing-body` resource for
// this `outgoing-response` can be retrieved at most once. Subsequent
// calls will return error.
//
//	body: func() -> result<outgoing-body>
//
//go:nosplit
func (self OutgoingResponse) Body() cm.OKResult[OutgoingBody, struct{}] {
	var result cm.OKResult[OutgoingBody, struct{}]
	self.wasmimport_Body(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-response.body
//go:noescape
func (self OutgoingResponse) wasmimport_Body(result *cm.OKResult[OutgoingBody, struct{}])

// Headers represents method "headers".
//
// Get the headers associated with the Request.
//
// The returned `headers` resource is immutable: `set`, `append`, and
// `delete` operations will fail with `header-error.immutable`.
//
// This headers resource is a child: it must be dropped before the parent
// `outgoing-request` is dropped, or its ownership is transfered to
// another component by e.g. `outgoing-handler.handle`.
//
//	headers: func() -> headers
//
//go:nosplit
func (self OutgoingResponse) Headers() Headers {
	return self.wasmimport_Headers()
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-response.headers
//go:noescape
func (self OutgoingResponse) wasmimport_Headers() Headers

// SetStatusCode represents method "set-status-code".
//
// Set the HTTP Status Code for the Response. Fails if the status-code
// given is not a valid http status code.
//
//	set-status-code: func(status-code: status-code) -> result
//
//go:nosplit
func (self OutgoingResponse) SetStatusCode(statusCode StatusCode) cm.Result {
	return self.wasmimport_SetStatusCode(statusCode)
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-response.set-status-code
//go:noescape
func (self OutgoingResponse) wasmimport_SetStatusCode(statusCode StatusCode) cm.Result

// StatusCode represents method "status-code".
//
// Get the HTTP Status Code for the Response.
//
//	status-code: func() -> status-code
//
//go:nosplit
func (self OutgoingResponse) StatusCode() StatusCode {
	return self.wasmimport_StatusCode()
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-response.status-code
//go:noescape
func (self OutgoingResponse) wasmimport_StatusCode() StatusCode

// OutgoingBody represents the resource "wasi:http/types@0.2.0#outgoing-body".
//
// Represents an outgoing HTTP Request or Response's Body.
//
// A body has both its contents - a stream of bytes - and a (possibly
// empty) set of trailers, inducating the full contents of the body
// have been sent. This resource represents the contents as an
// `output-stream` child resource, and the completion of the body (with
// optional trailers) with a static function that consumes the
// `outgoing-body` resource, and ensures that the user of this interface
// may not write to the body contents after the body has been finished.
//
// If the user code drops this resource, as opposed to calling the static
// method `finish`, the implementation should treat the body as incomplete,
// and that an error has occured. The implementation should propogate this
// error to the HTTP protocol by whatever means it has available,
// including: corrupting the body on the wire, aborting the associated
// Request, or sending a late status code for the Response.
//
//	resource outgoing-body
type OutgoingBody cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self OutgoingBody) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]outgoing-body
//go:noescape
func (self OutgoingBody) wasmimport_ResourceDrop()

// OutgoingBodyFinish represents static function "finish".
//
// Finalize an outgoing body, optionally providing trailers. This must be
// called to signal that the response is complete. If the `outgoing-body`
// is dropped without calling `outgoing-body.finalize`, the implementation
// should treat the body as corrupted.
//
// Fails if the body's `outgoing-request` or `outgoing-response` was
// constructed with a Content-Length header, and the contents written
// to the body (via `write`) does not match the value given in the
// Content-Length.
//
//	finish: static func(this: outgoing-body, trailers: option<trailers>) -> result<_,
//	error-code>
//
//go:nosplit
func OutgoingBodyFinish(this OutgoingBody, trailers cm.Option[Trailers]) cm.ErrResult[struct{}, ErrorCode] {
	var result cm.ErrResult[struct{}, ErrorCode]
	wasmimport_OutgoingBodyFinish(this, trailers, &result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [static]outgoing-body.finish
//go:noescape
func wasmimport_OutgoingBodyFinish(this OutgoingBody, trailers cm.Option[Trailers], result *cm.ErrResult[struct{}, ErrorCode])

// Write represents method "write".
//
// Returns a stream for writing the body contents.
//
// The returned `output-stream` is a child resource: it must be dropped
// before the parent `outgoing-body` resource is dropped (or finished),
// otherwise the `outgoing-body` drop or `finish` will trap.
//
// Returns success on the first call: the `output-stream` resource for
// this `outgoing-body` may be retrieved at most once. Subsequent calls
// will return error.
//
//	write: func() -> result<output-stream>
//
//go:nosplit
func (self OutgoingBody) Write() cm.OKResult[OutputStream, struct{}] {
	var result cm.OKResult[OutputStream, struct{}]
	self.wasmimport_Write(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]outgoing-body.write
//go:noescape
func (self OutgoingBody) wasmimport_Write(result *cm.OKResult[OutputStream, struct{}])

// FutureIncomingResponse represents the resource "wasi:http/types@0.2.0#future-incoming-response".
//
// Represents a future which may eventaully return an incoming HTTP
// Response, or an error.
//
// This resource is returned by the `wasi:http/outgoing-handler` interface to
// provide the HTTP Response corresponding to the sent Request.
//
//	resource future-incoming-response
type FutureIncomingResponse cm.Resource

// ResourceDrop represents the Canonical ABI function "resource-drop".
//
// Drops a resource handle.
//
//go:nosplit
func (self FutureIncomingResponse) ResourceDrop() {
	self.wasmimport_ResourceDrop()
}

//go:wasmimport wasi:http/types@0.2.0 [resource-drop]future-incoming-response
//go:noescape
func (self FutureIncomingResponse) wasmimport_ResourceDrop()

// Get represents method "get".
//
// Returns the incoming HTTP Response, or an error, once one is ready.
//
// The outer `option` represents future readiness. Users can wait on this
// `option` to become `some` using the `subscribe` method.
//
// The outer `result` is used to retrieve the response or error at most
// once. It will be success on the first call in which the outer option
// is `some`, and error on subsequent calls.
//
// The inner `result` represents that either the incoming HTTP Response
// status and headers have recieved successfully, or that an error
// occured. Errors may also occur while consuming the response body,
// but those will be reported by the `incoming-body` and its
// `output-stream` child.
//
//	get: func() -> option<result<result<incoming-response, error-code>>>
//
//go:nosplit
func (self FutureIncomingResponse) Get() cm.Option[cm.OKResult[cm.ErrResult[IncomingResponse, ErrorCode], struct{}]] {
	var result cm.Option[cm.OKResult[cm.ErrResult[IncomingResponse, ErrorCode], struct{}]]
	self.wasmimport_Get(&result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 [method]future-incoming-response.get
//go:noescape
func (self FutureIncomingResponse) wasmimport_Get(result *cm.Option[cm.OKResult[cm.ErrResult[IncomingResponse, ErrorCode], struct{}]])

// Subscribe represents method "subscribe".
//
// Returns a pollable which becomes ready when either the Response has
// been received, or an error has occured. When this pollable is ready,
// the `get` method will return `some`.
//
//	subscribe: func() -> pollable
//
//go:nosplit
func (self FutureIncomingResponse) Subscribe() Pollable {
	return self.wasmimport_Subscribe()
}

//go:wasmimport wasi:http/types@0.2.0 [method]future-incoming-response.subscribe
//go:noescape
func (self FutureIncomingResponse) wasmimport_Subscribe() Pollable

// HTTPErrorCode represents function "wasi:http/types@0.2.0#http-error-code".
//
// Attempts to extract a http-related `error` from the wasi:io `error`
// provided.
//
// Stream operations which return
// `wasi:io/stream/stream-error::last-operation-failed` have a payload of
// type `wasi:io/error/error` with more information about the operation
// that failed. This payload can be passed through to this function to see
// if there's http-related information about the error to return.
//
// Note that this function is fallible because not all io-errors are
// http-related errors.
//
//	http-error-code: func(err: borrow<io-error>) -> option<error-code>
//
//go:nosplit
func HTTPErrorCode(err IOError) cm.Option[ErrorCode] {
	var result cm.Option[ErrorCode]
	wasmimport_HTTPErrorCode(err, &result)
	return result
}

//go:wasmimport wasi:http/types@0.2.0 http-error-code
//go:noescape
func wasmimport_HTTPErrorCode(err IOError, result *cm.Option[ErrorCode])
